Ictshop/Controllers/DonhangsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Ictshop.Models;

namespace Ictshop.Controllers
{
    public class DonhangsController : Controller
    {
        private QLdienthoaiEntities db = new QLdienthoaiEntities();

        // GET: Donhangs
        // Hiển thị danh sách đơn hàng
        public ActionResult Index()
        {
            //Kiểm tra đang đăng nhập
           if (Session["use"] == null || Session["use"].ToString() == "")
            {
                return RedirectToAction("GuestOrder");
           }
            Nguoidung kh = (Nguoidung)Session["use"];
            int maND = kh.MaNguoiDung;
            var donhangs = db.Donhangs.Include(d => d.Nguoidung).Where(d=>d.MaNguoidung == maND);
            return View(donhangs.ToList());
        }

        // GET: Donhangs/Details/5
        //Hiển thị chi tiết đơn hàng
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Donhang donhang = db.Donhangs.Find(id);
            var chitiet = db.Chitietdonhangs.Include(d => d.Sanpham).Where(d=> d.Madon == id).ToList();
            if (donhang == null)
            {
                return HttpNotFound();
            }
            return View(chitiet);
        }
        // GET: Donhangs/Create
        // Tạo đơn hàng cho người dùng không đăng nhập
        public ActionResult Create()
        {
            ViewBag.MaNguoiDung = new SelectList(db.Nguoidungs, "MaNguoiDung", "Hoten");
            return View();
        }

        // POST: Donhangs/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Madon,Ngaydat,Tinhtrang,MaNguoidung,Thanhtoan,Diachinhanhang,Tongtien,GuestEmail")] Donhang donhang)
        {
            if (ModelState.IsValid)
            {
                db.Donhangs.Add(donhang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaNguoiDung = new SelectList(db.Nguoidungs, "MaNguoiDung", "Hoten", donhang.MaNguoidung);
            return View(donhang);
        }

        // GET: Donhangs/GuestOrder
        // Trang để người dùng không đăng nhập xem đơn hàng của họ
        public ActionResult GuestOrder()
        {
            return View();
        }

        // POST: Donhangs/GuestOrder
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GuestOrder(string email)
        {
            var donhangs = db.Donhangs.Include(d => d.Nguoidung).Where(d => d.Nguoidung.Email == email);
            return View("GuestOrderList", donhangs.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Ictshop/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SB Admin</title>
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    @*<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />*@
    <link href="~/Areas/Assets/dist/css/styles.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>

    <style type="text/css">
        .menu1{
            color:white;
            padding-left:20px;
        }
    </style>
</head>
<body class="sb-nav-fixed">
    @{ var u = Session["use"] as Ictshop.Models.Nguoidung; }

    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-success">
        <h3>@Html.ActionLink("ICT SHOP", "Index", "Home", new { @class = "menu1" })</h3>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button><!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>

        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a  class="dropdown-item" style="color:red" href="@Url.Action("Details", "Nguoidungs", new { id = u.MaNguoiDung  })"> Xin chào : @u.Email</a>

                    <div class="dropdown-divider"></div>
                    <a  class="dropdown-item" href="/User/DangXuat"> ĐĂNG XUẤT</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading" style="color:red"> <h5>MENU</h5></div>
                        <div style="padding-left:20px">
                            @*@Html.ActionLink("Sản phẩm", "Index", "Home", new { @style = "color:white;" })*@

                            @Html.ActionLink("Sản phẩm", "Index", "Home", null, new { @style = "color:white;" })
                            @*<a class="nav-link" href="@Url.Action("Index", "Home")"> <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>Sản phẩm</a>*@

                        </div>

                        <br />
                        <div style="padding-left:20px">
                            @Html.ActionLink("Hãng sản xuất", "Index", "Hangsanxuats", null, new { @style = "color:white;" })
                        </div>
                        <br />
                        <div style="padding-left:20px">
                            @Html.ActionLink("Hệ điều hành", "Index", "Hedieuhanhs", null, new { @style = "color:white;" })
                        </div>
                        <br />
                        <div style="padding-left:20px">
                            @Html.ActionLink("Người dùng", "Index", "Nguoidungs", null, new { @style = "color:white;" })
                        </div>
                        <br />
                        <div style="padding-left:20px">
                            @Html.ActionLink("Phân quyền", "Index", "Phanquyens", null, new { @style = "color:white;" })
                        </div>
                        <br />

                        <div style="padding-left:20px">
                            @Html.ActionLink("Đơn hàng", "Index", "Donhangs", null, new { @style = "color:white;" })
                        </div>

                        <br />

                        <div style="padding-left:20px">
                            @Html.ActionLink("Thống kê", "Index", "Thongkes", null, new { @style = "color:white;" })
                        </div>


                        @*<a class="nav-link" href="Home">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Hãng sản xuất
                            </a>*@
                    </div>
                </div>

                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    IctShop
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; IctShop 2021</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/Areas/Assets/dist/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="~/Areas/Assets/dist/assets/demo/chart-area-demo.js"></script>
    <script src="~/Areas/Assets/dist/assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="~/Areas/Assets/dist/assets/demo/datatables-demo.js"></script>
</body>
</html>